### PR TITLE
change password support

### PR DESCRIPTION
**Pull request by huglester**
Hello,

this is initial support to change password.

Form handler could be improved I think?
```php
$user = $request->user();
        $user->password = $builder->getFormValue('password_new');
        $user->save();
```

Also checking for old password: \Anomaly\UsersModule\User\Validation\ValidateCurrentPassword probably could be somehow improved.

I was not sure of the correct way to check 'login' field, so we actually compare current users login + password provided...

Maybe we should just check current users ID, then find this user in db, and compare the pass somehow?

Thanks :)

### CODE REVIEW

**Comment by RyanThompson** [comment]
Specially when you consider single sign in and stuff.. I don't like the idea of "old password" requirements. Thoughts?

**Comment by huglester** [comment]
Well, most people do have those 'remember me' functions. And probably because of this, you are asked for old password...

Twitter for example asks for current password. I think most of providers to this

**Comment by huglester** [comment]
so where did this end up?
you just set up 'New password' without old one?

**Comment by RyanThompson** [comment]
I feel like the reset password link should be used for this? Let's take this to an issue though cause I will need to clean up and master is getting deleted like.. now lol. I think I like this idea but I am not sure. Seems like most systems use an email link approach.

**Comment by huglester** [comment]
Well these are different. This is not forgot password.. this is change password for currently ligged in user. Or if you want to change a pass you just press forgot password?:) 

I think not everyone could think of this way... it is too developish:D

**Pull request closed without merging**
